apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-app
type: Opaque
stringData:
  MONGO_URI: "replace-with-mongodb-uri"
  REDIS_URL: "replace-with-redis-url"
  JWT_ACCESS_SECRET: "replace-with-jwt-access-secret"
  JWT_REFRESH_SECRET: "replace-with-jwt-refresh-secret"
  GOOGLE_CLIENT_ID: "replace-with-google-client-id"
  GOOGLE_CLIENT_SECRET: "replace-with-google-client-secret"
  GOOGLE_CALLBACK_URL: "replace-with-google-callback-url"